# Generated by Django 4.2.2 on 2025-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
